ALTER TABLE DAT_TOUR
ADD ID_LOAI INT NOT NULL;

ALTER TABLE DAT_TOUR
ADD CONSTRAINT FK_DAT_TOUR_LOAI_TOUR
FOREIGN KEY (ID_LOAI) REFERENCES LOAI_TOUR(ID_LOAI);

DBCC CHECKIDENT ('[dbo].[LOAI_TOUR]', RESEED, 2);

DBCC CHECKIDENT ('[dbo].[TRANG_THAI]', RESEED, 0);

SELECT IDENT_CURRENT('TOUR')

DBCC CHECKIDENT ('[dbo].[TOUR]', RESEED, 1);

ALTER TABLE TOUR
ADD STT INT IDENTITY(1,1);

CREATE TABLE [dbo].[TRANG_THAI_THANH_TOAN] (
    [ID_TRANG_THAI] INT PRIMARY KEY IDENTITY(1, 1),
    [TEN_TRANG_THAI] NVARCHAR(20) NOT NULL
);

INSERT INTO [dbo].[TRANG_THAI_THANH_TOAN] (TEN_TRANG_THAI)
VALUES (N'Đã Thanh Toán'), (N'Chưa Thanh Toán');

EXEC sp_rename 'TRANG_THAI', 'TRANG_THAI_TOUR';

CREATE TABLE [dbo].[TRANG_THAI_TOUR] (
    [ID_TRANG_THAI]  INT           IDENTITY (1, 1) NOT NULL,
    [TEN_TRANG_THAI] NVARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID_TRANG_THAI] ASC)
);

ALTER TABLE [dbo].[THANH_TOAN]
ADD [ID_TRANG_THAI] INT NOT NULL DEFAULT (1);

ALTER TABLE [dbo].[THANH_TOAN]
ADD CONSTRAINT FK_THANH_TOAN_TRANG_THAI
FOREIGN KEY (ID_TRANG_THAI) REFERENCES TRANG_THAI_THANH_TOAN(ID_TRANG_THAI);