#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Tour.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="pacifictravel")]
	public partial class databaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertADMIN(ADMIN instance);
    partial void UpdateADMIN(ADMIN instance);
    partial void DeleteADMIN(ADMIN instance);
    partial void InsertTRANG_THAI_THANH_TOAN(TRANG_THAI_THANH_TOAN instance);
    partial void UpdateTRANG_THAI_THANH_TOAN(TRANG_THAI_THANH_TOAN instance);
    partial void DeleteTRANG_THAI_THANH_TOAN(TRANG_THAI_THANH_TOAN instance);
    partial void InsertBAI_VIET(BAI_VIET instance);
    partial void UpdateBAI_VIET(BAI_VIET instance);
    partial void DeleteBAI_VIET(BAI_VIET instance);
    partial void InsertDANH_GIA(DANH_GIA instance);
    partial void UpdateDANH_GIA(DANH_GIA instance);
    partial void DeleteDANH_GIA(DANH_GIA instance);
    partial void InsertDAT_TOUR(DAT_TOUR instance);
    partial void UpdateDAT_TOUR(DAT_TOUR instance);
    partial void DeleteDAT_TOUR(DAT_TOUR instance);
    partial void InsertHUONGDANVIEN(HUONGDANVIEN instance);
    partial void UpdateHUONGDANVIEN(HUONGDANVIEN instance);
    partial void DeleteHUONGDANVIEN(HUONGDANVIEN instance);
    partial void InsertLOAI_TOUR(LOAI_TOUR instance);
    partial void UpdateLOAI_TOUR(LOAI_TOUR instance);
    partial void DeleteLOAI_TOUR(LOAI_TOUR instance);
    partial void InsertPHUONG_THUC_THANH_TOAN(PHUONG_THUC_THANH_TOAN instance);
    partial void UpdatePHUONG_THUC_THANH_TOAN(PHUONG_THUC_THANH_TOAN instance);
    partial void DeletePHUONG_THUC_THANH_TOAN(PHUONG_THUC_THANH_TOAN instance);
    partial void InsertTOUR(TOUR instance);
    partial void UpdateTOUR(TOUR instance);
    partial void DeleteTOUR(TOUR instance);
    partial void InsertTHANH_TOAN(THANH_TOAN instance);
    partial void UpdateTHANH_TOAN(THANH_TOAN instance);
    partial void DeleteTHANH_TOAN(THANH_TOAN instance);
    partial void InsertTHANH_VIEN(THANH_VIEN instance);
    partial void UpdateTHANH_VIEN(THANH_VIEN instance);
    partial void DeleteTHANH_VIEN(THANH_VIEN instance);
    partial void InsertTRANG_THAI_TOUR(TRANG_THAI_TOUR instance);
    partial void UpdateTRANG_THAI_TOUR(TRANG_THAI_TOUR instance);
    partial void DeleteTRANG_THAI_TOUR(TRANG_THAI_TOUR instance);
    #endregion
		
		public databaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ADMIN> ADMINs
		{
			get
			{
				return this.GetTable<ADMIN>();
			}
		}
		
		public System.Data.Linq.Table<TRANG_THAI_THANH_TOAN> TRANG_THAI_THANH_TOANs
		{
			get
			{
				return this.GetTable<TRANG_THAI_THANH_TOAN>();
			}
		}
		
		public System.Data.Linq.Table<BAI_VIET> BAI_VIETs
		{
			get
			{
				return this.GetTable<BAI_VIET>();
			}
		}
		
		public System.Data.Linq.Table<DANH_GIA> DANH_GIAs
		{
			get
			{
				return this.GetTable<DANH_GIA>();
			}
		}
		
		public System.Data.Linq.Table<DAT_TOUR> DAT_TOURs
		{
			get
			{
				return this.GetTable<DAT_TOUR>();
			}
		}
		
		public System.Data.Linq.Table<HUONGDANVIEN> HUONGDANVIENs
		{
			get
			{
				return this.GetTable<HUONGDANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<LOAI_TOUR> LOAI_TOURs
		{
			get
			{
				return this.GetTable<LOAI_TOUR>();
			}
		}
		
		public System.Data.Linq.Table<PHUONG_THUC_THANH_TOAN> PHUONG_THUC_THANH_TOANs
		{
			get
			{
				return this.GetTable<PHUONG_THUC_THANH_TOAN>();
			}
		}
		
		public System.Data.Linq.Table<TOUR> TOURs
		{
			get
			{
				return this.GetTable<TOUR>();
			}
		}
		
		public System.Data.Linq.Table<THANH_TOAN> THANH_TOANs
		{
			get
			{
				return this.GetTable<THANH_TOAN>();
			}
		}
		
		public System.Data.Linq.Table<THANH_VIEN> THANH_VIENs
		{
			get
			{
				return this.GetTable<THANH_VIEN>();
			}
		}
		
		public System.Data.Linq.Table<TRANG_THAI_TOUR> TRANG_THAI_TOURs
		{
			get
			{
				return this.GetTable<TRANG_THAI_TOUR>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADMIN")]
	public partial class ADMIN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_ADMIN;
		
		private System.Nullable<int> _ID_THANH_VIEN;
		
		private EntitySet<BAI_VIET> _BAI_VIETs;
		
		private EntityRef<THANH_VIEN> _THANH_VIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ADMINChanging(int value);
    partial void OnID_ADMINChanged();
    partial void OnID_THANH_VIENChanging(System.Nullable<int> value);
    partial void OnID_THANH_VIENChanged();
    #endregion
		
		public ADMIN()
		{
			this._BAI_VIETs = new EntitySet<BAI_VIET>(new Action<BAI_VIET>(this.attach_BAI_VIETs), new Action<BAI_VIET>(this.detach_BAI_VIETs));
			this._THANH_VIEN = default(EntityRef<THANH_VIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ADMIN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_ADMIN
		{
			get
			{
				return this._ID_ADMIN;
			}
			set
			{
				if ((this._ID_ADMIN != value))
				{
					this.OnID_ADMINChanging(value);
					this.SendPropertyChanging();
					this._ID_ADMIN = value;
					this.SendPropertyChanged("ID_ADMIN");
					this.OnID_ADMINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_THANH_VIEN", DbType="Int")]
		public System.Nullable<int> ID_THANH_VIEN
		{
			get
			{
				return this._ID_THANH_VIEN;
			}
			set
			{
				if ((this._ID_THANH_VIEN != value))
				{
					if (this._THANH_VIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_THANH_VIENChanging(value);
					this.SendPropertyChanging();
					this._ID_THANH_VIEN = value;
					this.SendPropertyChanged("ID_THANH_VIEN");
					this.OnID_THANH_VIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ADMIN_BAI_VIET", Storage="_BAI_VIETs", ThisKey="ID_ADMIN", OtherKey="ID_ADMIN")]
		public EntitySet<BAI_VIET> BAI_VIETs
		{
			get
			{
				return this._BAI_VIETs;
			}
			set
			{
				this._BAI_VIETs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THANH_VIEN_ADMIN", Storage="_THANH_VIEN", ThisKey="ID_THANH_VIEN", OtherKey="ID_THANH_VIEN", IsForeignKey=true)]
		public THANH_VIEN THANH_VIEN
		{
			get
			{
				return this._THANH_VIEN.Entity;
			}
			set
			{
				THANH_VIEN previousValue = this._THANH_VIEN.Entity;
				if (((previousValue != value) 
							|| (this._THANH_VIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THANH_VIEN.Entity = null;
						previousValue.ADMINs.Remove(this);
					}
					this._THANH_VIEN.Entity = value;
					if ((value != null))
					{
						value.ADMINs.Add(this);
						this._ID_THANH_VIEN = value.ID_THANH_VIEN;
					}
					else
					{
						this._ID_THANH_VIEN = default(Nullable<int>);
					}
					this.SendPropertyChanged("THANH_VIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BAI_VIETs(BAI_VIET entity)
		{
			this.SendPropertyChanging();
			entity.ADMIN = this;
		}
		
		private void detach_BAI_VIETs(BAI_VIET entity)
		{
			this.SendPropertyChanging();
			entity.ADMIN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRANG_THAI_THANH_TOAN")]
	public partial class TRANG_THAI_THANH_TOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_TRANG_THAI;
		
		private string _TEN_TRANG_THAI;
		
		private EntitySet<THANH_TOAN> _THANH_TOANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_TRANG_THAIChanging(int value);
    partial void OnID_TRANG_THAIChanged();
    partial void OnTEN_TRANG_THAIChanging(string value);
    partial void OnTEN_TRANG_THAIChanged();
    #endregion
		
		public TRANG_THAI_THANH_TOAN()
		{
			this._THANH_TOANs = new EntitySet<THANH_TOAN>(new Action<THANH_TOAN>(this.attach_THANH_TOANs), new Action<THANH_TOAN>(this.detach_THANH_TOANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TRANG_THAI", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_TRANG_THAI
		{
			get
			{
				return this._ID_TRANG_THAI;
			}
			set
			{
				if ((this._ID_TRANG_THAI != value))
				{
					this.OnID_TRANG_THAIChanging(value);
					this.SendPropertyChanging();
					this._ID_TRANG_THAI = value;
					this.SendPropertyChanged("ID_TRANG_THAI");
					this.OnID_TRANG_THAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_TRANG_THAI", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TEN_TRANG_THAI
		{
			get
			{
				return this._TEN_TRANG_THAI;
			}
			set
			{
				if ((this._TEN_TRANG_THAI != value))
				{
					this.OnTEN_TRANG_THAIChanging(value);
					this.SendPropertyChanging();
					this._TEN_TRANG_THAI = value;
					this.SendPropertyChanged("TEN_TRANG_THAI");
					this.OnTEN_TRANG_THAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRANG_THAI_THANH_TOAN_THANH_TOAN", Storage="_THANH_TOANs", ThisKey="ID_TRANG_THAI", OtherKey="ID_TRANG_THAI")]
		public EntitySet<THANH_TOAN> THANH_TOANs
		{
			get
			{
				return this._THANH_TOANs;
			}
			set
			{
				this._THANH_TOANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_THANH_TOANs(THANH_TOAN entity)
		{
			this.SendPropertyChanging();
			entity.TRANG_THAI_THANH_TOAN = this;
		}
		
		private void detach_THANH_TOANs(THANH_TOAN entity)
		{
			this.SendPropertyChanging();
			entity.TRANG_THAI_THANH_TOAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BAI_VIET")]
	public partial class BAI_VIET : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_BAI_VIET;
		
		private System.Nullable<System.DateTime> _THOI_GIAN_TAO;
		
		private string _NOI_DUNG;
		
		private int _ID_ADMIN;
		
		private string _ANH_BIA_BAI_VIET;
		
		private EntityRef<ADMIN> _ADMIN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_BAI_VIETChanging(int value);
    partial void OnID_BAI_VIETChanged();
    partial void OnTHOI_GIAN_TAOChanging(System.Nullable<System.DateTime> value);
    partial void OnTHOI_GIAN_TAOChanged();
    partial void OnNOI_DUNGChanging(string value);
    partial void OnNOI_DUNGChanged();
    partial void OnID_ADMINChanging(int value);
    partial void OnID_ADMINChanged();
    partial void OnANH_BIA_BAI_VIETChanging(string value);
    partial void OnANH_BIA_BAI_VIETChanged();
    #endregion
		
		public BAI_VIET()
		{
			this._ADMIN = default(EntityRef<ADMIN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_BAI_VIET", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_BAI_VIET
		{
			get
			{
				return this._ID_BAI_VIET;
			}
			set
			{
				if ((this._ID_BAI_VIET != value))
				{
					this.OnID_BAI_VIETChanging(value);
					this.SendPropertyChanging();
					this._ID_BAI_VIET = value;
					this.SendPropertyChanged("ID_BAI_VIET");
					this.OnID_BAI_VIETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOI_GIAN_TAO", DbType="DateTime")]
		public System.Nullable<System.DateTime> THOI_GIAN_TAO
		{
			get
			{
				return this._THOI_GIAN_TAO;
			}
			set
			{
				if ((this._THOI_GIAN_TAO != value))
				{
					this.OnTHOI_GIAN_TAOChanging(value);
					this.SendPropertyChanging();
					this._THOI_GIAN_TAO = value;
					this.SendPropertyChanged("THOI_GIAN_TAO");
					this.OnTHOI_GIAN_TAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOI_DUNG", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string NOI_DUNG
		{
			get
			{
				return this._NOI_DUNG;
			}
			set
			{
				if ((this._NOI_DUNG != value))
				{
					this.OnNOI_DUNGChanging(value);
					this.SendPropertyChanging();
					this._NOI_DUNG = value;
					this.SendPropertyChanged("NOI_DUNG");
					this.OnNOI_DUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ADMIN", DbType="Int NOT NULL")]
		public int ID_ADMIN
		{
			get
			{
				return this._ID_ADMIN;
			}
			set
			{
				if ((this._ID_ADMIN != value))
				{
					if (this._ADMIN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ADMINChanging(value);
					this.SendPropertyChanging();
					this._ID_ADMIN = value;
					this.SendPropertyChanged("ID_ADMIN");
					this.OnID_ADMINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANH_BIA_BAI_VIET", DbType="NVarChar(255)")]
		public string ANH_BIA_BAI_VIET
		{
			get
			{
				return this._ANH_BIA_BAI_VIET;
			}
			set
			{
				if ((this._ANH_BIA_BAI_VIET != value))
				{
					this.OnANH_BIA_BAI_VIETChanging(value);
					this.SendPropertyChanging();
					this._ANH_BIA_BAI_VIET = value;
					this.SendPropertyChanged("ANH_BIA_BAI_VIET");
					this.OnANH_BIA_BAI_VIETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ADMIN_BAI_VIET", Storage="_ADMIN", ThisKey="ID_ADMIN", OtherKey="ID_ADMIN", IsForeignKey=true)]
		public ADMIN ADMIN
		{
			get
			{
				return this._ADMIN.Entity;
			}
			set
			{
				ADMIN previousValue = this._ADMIN.Entity;
				if (((previousValue != value) 
							|| (this._ADMIN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ADMIN.Entity = null;
						previousValue.BAI_VIETs.Remove(this);
					}
					this._ADMIN.Entity = value;
					if ((value != null))
					{
						value.BAI_VIETs.Add(this);
						this._ID_ADMIN = value.ID_ADMIN;
					}
					else
					{
						this._ID_ADMIN = default(int);
					}
					this.SendPropertyChanged("ADMIN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DANH_GIA")]
	public partial class DANH_GIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_DANH_GIA;
		
		private System.Nullable<int> _SO_LUONG_SAO;
		
		private string _NOI_DUNG_DANH_GIA;
		
		private string _ID_TOUR;
		
		private int _ID_THANH_VIEN;
		
		private EntityRef<TOUR> _TOUR;
		
		private EntityRef<THANH_VIEN> _THANH_VIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_DANH_GIAChanging(int value);
    partial void OnID_DANH_GIAChanged();
    partial void OnSO_LUONG_SAOChanging(System.Nullable<int> value);
    partial void OnSO_LUONG_SAOChanged();
    partial void OnNOI_DUNG_DANH_GIAChanging(string value);
    partial void OnNOI_DUNG_DANH_GIAChanged();
    partial void OnID_TOURChanging(string value);
    partial void OnID_TOURChanged();
    partial void OnID_THANH_VIENChanging(int value);
    partial void OnID_THANH_VIENChanged();
    #endregion
		
		public DANH_GIA()
		{
			this._TOUR = default(EntityRef<TOUR>);
			this._THANH_VIEN = default(EntityRef<THANH_VIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DANH_GIA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_DANH_GIA
		{
			get
			{
				return this._ID_DANH_GIA;
			}
			set
			{
				if ((this._ID_DANH_GIA != value))
				{
					this.OnID_DANH_GIAChanging(value);
					this.SendPropertyChanging();
					this._ID_DANH_GIA = value;
					this.SendPropertyChanged("ID_DANH_GIA");
					this.OnID_DANH_GIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SO_LUONG_SAO", DbType="Int")]
		public System.Nullable<int> SO_LUONG_SAO
		{
			get
			{
				return this._SO_LUONG_SAO;
			}
			set
			{
				if ((this._SO_LUONG_SAO != value))
				{
					this.OnSO_LUONG_SAOChanging(value);
					this.SendPropertyChanging();
					this._SO_LUONG_SAO = value;
					this.SendPropertyChanged("SO_LUONG_SAO");
					this.OnSO_LUONG_SAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOI_DUNG_DANH_GIA", DbType="NVarChar(500)")]
		public string NOI_DUNG_DANH_GIA
		{
			get
			{
				return this._NOI_DUNG_DANH_GIA;
			}
			set
			{
				if ((this._NOI_DUNG_DANH_GIA != value))
				{
					this.OnNOI_DUNG_DANH_GIAChanging(value);
					this.SendPropertyChanging();
					this._NOI_DUNG_DANH_GIA = value;
					this.SendPropertyChanged("NOI_DUNG_DANH_GIA");
					this.OnNOI_DUNG_DANH_GIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TOUR", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ID_TOUR
		{
			get
			{
				return this._ID_TOUR;
			}
			set
			{
				if ((this._ID_TOUR != value))
				{
					if (this._TOUR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_TOURChanging(value);
					this.SendPropertyChanging();
					this._ID_TOUR = value;
					this.SendPropertyChanged("ID_TOUR");
					this.OnID_TOURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_THANH_VIEN", DbType="Int NOT NULL")]
		public int ID_THANH_VIEN
		{
			get
			{
				return this._ID_THANH_VIEN;
			}
			set
			{
				if ((this._ID_THANH_VIEN != value))
				{
					if (this._THANH_VIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_THANH_VIENChanging(value);
					this.SendPropertyChanging();
					this._ID_THANH_VIEN = value;
					this.SendPropertyChanged("ID_THANH_VIEN");
					this.OnID_THANH_VIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOUR_DANH_GIA", Storage="_TOUR", ThisKey="ID_TOUR", OtherKey="ID_TOUR", IsForeignKey=true)]
		public TOUR TOUR
		{
			get
			{
				return this._TOUR.Entity;
			}
			set
			{
				TOUR previousValue = this._TOUR.Entity;
				if (((previousValue != value) 
							|| (this._TOUR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TOUR.Entity = null;
						previousValue.DANH_GIAs.Remove(this);
					}
					this._TOUR.Entity = value;
					if ((value != null))
					{
						value.DANH_GIAs.Add(this);
						this._ID_TOUR = value.ID_TOUR;
					}
					else
					{
						this._ID_TOUR = default(string);
					}
					this.SendPropertyChanged("TOUR");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THANH_VIEN_DANH_GIA", Storage="_THANH_VIEN", ThisKey="ID_THANH_VIEN", OtherKey="ID_THANH_VIEN", IsForeignKey=true)]
		public THANH_VIEN THANH_VIEN
		{
			get
			{
				return this._THANH_VIEN.Entity;
			}
			set
			{
				THANH_VIEN previousValue = this._THANH_VIEN.Entity;
				if (((previousValue != value) 
							|| (this._THANH_VIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THANH_VIEN.Entity = null;
						previousValue.DANH_GIAs.Remove(this);
					}
					this._THANH_VIEN.Entity = value;
					if ((value != null))
					{
						value.DANH_GIAs.Add(this);
						this._ID_THANH_VIEN = value.ID_THANH_VIEN;
					}
					else
					{
						this._ID_THANH_VIEN = default(int);
					}
					this.SendPropertyChanged("THANH_VIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DAT_TOUR")]
	public partial class DAT_TOUR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STT;
		
		private string _ID_DAT_TOUR;
		
		private System.Nullable<System.DateTime> _THOI_GIAN_DAT;
		
		private decimal _TONG_SO_TIEN;
		
		private string _ID_TOUR;
		
		private System.Nullable<int> _ID_THANH_TOAN;
		
		private System.Nullable<int> _ID_THANH_VIEN;
		
		private int _ID_LOAI;
		
		private EntityRef<LOAI_TOUR> _LOAI_TOUR;
		
		private EntityRef<TOUR> _TOUR;
		
		private EntityRef<THANH_TOAN> _THANH_TOAN;
		
		private EntityRef<THANH_VIEN> _THANH_VIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTTChanging(int value);
    partial void OnSTTChanged();
    partial void OnID_DAT_TOURChanging(string value);
    partial void OnID_DAT_TOURChanged();
    partial void OnTHOI_GIAN_DATChanging(System.Nullable<System.DateTime> value);
    partial void OnTHOI_GIAN_DATChanged();
    partial void OnTONG_SO_TIENChanging(decimal value);
    partial void OnTONG_SO_TIENChanged();
    partial void OnID_TOURChanging(string value);
    partial void OnID_TOURChanged();
    partial void OnID_THANH_TOANChanging(System.Nullable<int> value);
    partial void OnID_THANH_TOANChanged();
    partial void OnID_THANH_VIENChanging(System.Nullable<int> value);
    partial void OnID_THANH_VIENChanged();
    partial void OnID_LOAIChanging(int value);
    partial void OnID_LOAIChanged();
    #endregion
		
		public DAT_TOUR()
		{
			this._LOAI_TOUR = default(EntityRef<LOAI_TOUR>);
			this._TOUR = default(EntityRef<TOUR>);
			this._THANH_TOAN = default(EntityRef<THANH_TOAN>);
			this._THANH_VIEN = default(EntityRef<THANH_VIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DAT_TOUR", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_DAT_TOUR
		{
			get
			{
				return this._ID_DAT_TOUR;
			}
			set
			{
				if ((this._ID_DAT_TOUR != value))
				{
					this.OnID_DAT_TOURChanging(value);
					this.SendPropertyChanging();
					this._ID_DAT_TOUR = value;
					this.SendPropertyChanged("ID_DAT_TOUR");
					this.OnID_DAT_TOURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOI_GIAN_DAT", DbType="DateTime")]
		public System.Nullable<System.DateTime> THOI_GIAN_DAT
		{
			get
			{
				return this._THOI_GIAN_DAT;
			}
			set
			{
				if ((this._THOI_GIAN_DAT != value))
				{
					this.OnTHOI_GIAN_DATChanging(value);
					this.SendPropertyChanging();
					this._THOI_GIAN_DAT = value;
					this.SendPropertyChanged("THOI_GIAN_DAT");
					this.OnTHOI_GIAN_DATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONG_SO_TIEN", DbType="Decimal(18,2) NOT NULL")]
		public decimal TONG_SO_TIEN
		{
			get
			{
				return this._TONG_SO_TIEN;
			}
			set
			{
				if ((this._TONG_SO_TIEN != value))
				{
					this.OnTONG_SO_TIENChanging(value);
					this.SendPropertyChanging();
					this._TONG_SO_TIEN = value;
					this.SendPropertyChanged("TONG_SO_TIEN");
					this.OnTONG_SO_TIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TOUR", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ID_TOUR
		{
			get
			{
				return this._ID_TOUR;
			}
			set
			{
				if ((this._ID_TOUR != value))
				{
					if (this._TOUR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_TOURChanging(value);
					this.SendPropertyChanging();
					this._ID_TOUR = value;
					this.SendPropertyChanged("ID_TOUR");
					this.OnID_TOURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_THANH_TOAN", DbType="Int")]
		public System.Nullable<int> ID_THANH_TOAN
		{
			get
			{
				return this._ID_THANH_TOAN;
			}
			set
			{
				if ((this._ID_THANH_TOAN != value))
				{
					if (this._THANH_TOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_THANH_TOANChanging(value);
					this.SendPropertyChanging();
					this._ID_THANH_TOAN = value;
					this.SendPropertyChanged("ID_THANH_TOAN");
					this.OnID_THANH_TOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_THANH_VIEN", DbType="Int")]
		public System.Nullable<int> ID_THANH_VIEN
		{
			get
			{
				return this._ID_THANH_VIEN;
			}
			set
			{
				if ((this._ID_THANH_VIEN != value))
				{
					if (this._THANH_VIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_THANH_VIENChanging(value);
					this.SendPropertyChanging();
					this._ID_THANH_VIEN = value;
					this.SendPropertyChanged("ID_THANH_VIEN");
					this.OnID_THANH_VIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOAI", DbType="Int NOT NULL")]
		public int ID_LOAI
		{
			get
			{
				return this._ID_LOAI;
			}
			set
			{
				if ((this._ID_LOAI != value))
				{
					if (this._LOAI_TOUR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_LOAIChanging(value);
					this.SendPropertyChanging();
					this._ID_LOAI = value;
					this.SendPropertyChanged("ID_LOAI");
					this.OnID_LOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAI_TOUR_DAT_TOUR", Storage="_LOAI_TOUR", ThisKey="ID_LOAI", OtherKey="ID_LOAI", IsForeignKey=true)]
		public LOAI_TOUR LOAI_TOUR
		{
			get
			{
				return this._LOAI_TOUR.Entity;
			}
			set
			{
				LOAI_TOUR previousValue = this._LOAI_TOUR.Entity;
				if (((previousValue != value) 
							|| (this._LOAI_TOUR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAI_TOUR.Entity = null;
						previousValue.DAT_TOURs.Remove(this);
					}
					this._LOAI_TOUR.Entity = value;
					if ((value != null))
					{
						value.DAT_TOURs.Add(this);
						this._ID_LOAI = value.ID_LOAI;
					}
					else
					{
						this._ID_LOAI = default(int);
					}
					this.SendPropertyChanged("LOAI_TOUR");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOUR_DAT_TOUR", Storage="_TOUR", ThisKey="ID_TOUR", OtherKey="ID_TOUR", IsForeignKey=true)]
		public TOUR TOUR
		{
			get
			{
				return this._TOUR.Entity;
			}
			set
			{
				TOUR previousValue = this._TOUR.Entity;
				if (((previousValue != value) 
							|| (this._TOUR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TOUR.Entity = null;
						previousValue.DAT_TOURs.Remove(this);
					}
					this._TOUR.Entity = value;
					if ((value != null))
					{
						value.DAT_TOURs.Add(this);
						this._ID_TOUR = value.ID_TOUR;
					}
					else
					{
						this._ID_TOUR = default(string);
					}
					this.SendPropertyChanged("TOUR");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THANH_TOAN_DAT_TOUR", Storage="_THANH_TOAN", ThisKey="ID_THANH_TOAN", OtherKey="ID_THANH_TOAN", IsForeignKey=true)]
		public THANH_TOAN THANH_TOAN
		{
			get
			{
				return this._THANH_TOAN.Entity;
			}
			set
			{
				THANH_TOAN previousValue = this._THANH_TOAN.Entity;
				if (((previousValue != value) 
							|| (this._THANH_TOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THANH_TOAN.Entity = null;
						previousValue.DAT_TOURs.Remove(this);
					}
					this._THANH_TOAN.Entity = value;
					if ((value != null))
					{
						value.DAT_TOURs.Add(this);
						this._ID_THANH_TOAN = value.ID_THANH_TOAN;
					}
					else
					{
						this._ID_THANH_TOAN = default(Nullable<int>);
					}
					this.SendPropertyChanged("THANH_TOAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THANH_VIEN_DAT_TOUR", Storage="_THANH_VIEN", ThisKey="ID_THANH_VIEN", OtherKey="ID_THANH_VIEN", IsForeignKey=true)]
		public THANH_VIEN THANH_VIEN
		{
			get
			{
				return this._THANH_VIEN.Entity;
			}
			set
			{
				THANH_VIEN previousValue = this._THANH_VIEN.Entity;
				if (((previousValue != value) 
							|| (this._THANH_VIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THANH_VIEN.Entity = null;
						previousValue.DAT_TOURs.Remove(this);
					}
					this._THANH_VIEN.Entity = value;
					if ((value != null))
					{
						value.DAT_TOURs.Add(this);
						this._ID_THANH_VIEN = value.ID_THANH_VIEN;
					}
					else
					{
						this._ID_THANH_VIEN = default(Nullable<int>);
					}
					this.SendPropertyChanged("THANH_VIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HUONGDANVIEN")]
	public partial class HUONGDANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_HDV;
		
		private string _HO_TEN_HDV;
		
		private string _SDT_HDV;
		
		private string _EMAIL_HDV;
		
		private string _DIA_CHI_HDV;
		
		private EntitySet<TOUR> _TOURs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_HDVChanging(int value);
    partial void OnID_HDVChanged();
    partial void OnHO_TEN_HDVChanging(string value);
    partial void OnHO_TEN_HDVChanged();
    partial void OnSDT_HDVChanging(string value);
    partial void OnSDT_HDVChanged();
    partial void OnEMAIL_HDVChanging(string value);
    partial void OnEMAIL_HDVChanged();
    partial void OnDIA_CHI_HDVChanging(string value);
    partial void OnDIA_CHI_HDVChanged();
    #endregion
		
		public HUONGDANVIEN()
		{
			this._TOURs = new EntitySet<TOUR>(new Action<TOUR>(this.attach_TOURs), new Action<TOUR>(this.detach_TOURs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_HDV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_HDV
		{
			get
			{
				return this._ID_HDV;
			}
			set
			{
				if ((this._ID_HDV != value))
				{
					this.OnID_HDVChanging(value);
					this.SendPropertyChanging();
					this._ID_HDV = value;
					this.SendPropertyChanged("ID_HDV");
					this.OnID_HDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HO_TEN_HDV", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string HO_TEN_HDV
		{
			get
			{
				return this._HO_TEN_HDV;
			}
			set
			{
				if ((this._HO_TEN_HDV != value))
				{
					this.OnHO_TEN_HDVChanging(value);
					this.SendPropertyChanging();
					this._HO_TEN_HDV = value;
					this.SendPropertyChanged("HO_TEN_HDV");
					this.OnHO_TEN_HDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT_HDV", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string SDT_HDV
		{
			get
			{
				return this._SDT_HDV;
			}
			set
			{
				if ((this._SDT_HDV != value))
				{
					this.OnSDT_HDVChanging(value);
					this.SendPropertyChanging();
					this._SDT_HDV = value;
					this.SendPropertyChanged("SDT_HDV");
					this.OnSDT_HDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL_HDV", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string EMAIL_HDV
		{
			get
			{
				return this._EMAIL_HDV;
			}
			set
			{
				if ((this._EMAIL_HDV != value))
				{
					this.OnEMAIL_HDVChanging(value);
					this.SendPropertyChanging();
					this._EMAIL_HDV = value;
					this.SendPropertyChanged("EMAIL_HDV");
					this.OnEMAIL_HDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIA_CHI_HDV", DbType="NVarChar(200)")]
		public string DIA_CHI_HDV
		{
			get
			{
				return this._DIA_CHI_HDV;
			}
			set
			{
				if ((this._DIA_CHI_HDV != value))
				{
					this.OnDIA_CHI_HDVChanging(value);
					this.SendPropertyChanging();
					this._DIA_CHI_HDV = value;
					this.SendPropertyChanged("DIA_CHI_HDV");
					this.OnDIA_CHI_HDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HUONGDANVIEN_TOUR", Storage="_TOURs", ThisKey="ID_HDV", OtherKey="ID_HDV")]
		public EntitySet<TOUR> TOURs
		{
			get
			{
				return this._TOURs;
			}
			set
			{
				this._TOURs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TOURs(TOUR entity)
		{
			this.SendPropertyChanging();
			entity.HUONGDANVIEN = this;
		}
		
		private void detach_TOURs(TOUR entity)
		{
			this.SendPropertyChanging();
			entity.HUONGDANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAI_TOUR")]
	public partial class LOAI_TOUR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_LOAI;
		
		private string _TEN_LOAI;
		
		private EntitySet<DAT_TOUR> _DAT_TOURs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_LOAIChanging(int value);
    partial void OnID_LOAIChanged();
    partial void OnTEN_LOAIChanging(string value);
    partial void OnTEN_LOAIChanged();
    #endregion
		
		public LOAI_TOUR()
		{
			this._DAT_TOURs = new EntitySet<DAT_TOUR>(new Action<DAT_TOUR>(this.attach_DAT_TOURs), new Action<DAT_TOUR>(this.detach_DAT_TOURs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOAI", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_LOAI
		{
			get
			{
				return this._ID_LOAI;
			}
			set
			{
				if ((this._ID_LOAI != value))
				{
					this.OnID_LOAIChanging(value);
					this.SendPropertyChanging();
					this._ID_LOAI = value;
					this.SendPropertyChanged("ID_LOAI");
					this.OnID_LOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_LOAI", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TEN_LOAI
		{
			get
			{
				return this._TEN_LOAI;
			}
			set
			{
				if ((this._TEN_LOAI != value))
				{
					this.OnTEN_LOAIChanging(value);
					this.SendPropertyChanging();
					this._TEN_LOAI = value;
					this.SendPropertyChanged("TEN_LOAI");
					this.OnTEN_LOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAI_TOUR_DAT_TOUR", Storage="_DAT_TOURs", ThisKey="ID_LOAI", OtherKey="ID_LOAI")]
		public EntitySet<DAT_TOUR> DAT_TOURs
		{
			get
			{
				return this._DAT_TOURs;
			}
			set
			{
				this._DAT_TOURs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DAT_TOURs(DAT_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.LOAI_TOUR = this;
		}
		
		private void detach_DAT_TOURs(DAT_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.LOAI_TOUR = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHUONG_THUC_THANH_TOAN")]
	public partial class PHUONG_THUC_THANH_TOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_PHUONG_THUC;
		
		private string _TEN_PHUONG_THUC;
		
		private EntitySet<THANH_TOAN> _THANH_TOANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PHUONG_THUCChanging(int value);
    partial void OnID_PHUONG_THUCChanged();
    partial void OnTEN_PHUONG_THUCChanging(string value);
    partial void OnTEN_PHUONG_THUCChanged();
    #endregion
		
		public PHUONG_THUC_THANH_TOAN()
		{
			this._THANH_TOANs = new EntitySet<THANH_TOAN>(new Action<THANH_TOAN>(this.attach_THANH_TOANs), new Action<THANH_TOAN>(this.detach_THANH_TOANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PHUONG_THUC", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_PHUONG_THUC
		{
			get
			{
				return this._ID_PHUONG_THUC;
			}
			set
			{
				if ((this._ID_PHUONG_THUC != value))
				{
					this.OnID_PHUONG_THUCChanging(value);
					this.SendPropertyChanging();
					this._ID_PHUONG_THUC = value;
					this.SendPropertyChanged("ID_PHUONG_THUC");
					this.OnID_PHUONG_THUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_PHUONG_THUC", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TEN_PHUONG_THUC
		{
			get
			{
				return this._TEN_PHUONG_THUC;
			}
			set
			{
				if ((this._TEN_PHUONG_THUC != value))
				{
					this.OnTEN_PHUONG_THUCChanging(value);
					this.SendPropertyChanging();
					this._TEN_PHUONG_THUC = value;
					this.SendPropertyChanged("TEN_PHUONG_THUC");
					this.OnTEN_PHUONG_THUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHUONG_THUC_THANH_TOAN_THANH_TOAN", Storage="_THANH_TOANs", ThisKey="ID_PHUONG_THUC", OtherKey="ID_PHUONG_THUC")]
		public EntitySet<THANH_TOAN> THANH_TOANs
		{
			get
			{
				return this._THANH_TOANs;
			}
			set
			{
				this._THANH_TOANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_THANH_TOANs(THANH_TOAN entity)
		{
			this.SendPropertyChanging();
			entity.PHUONG_THUC_THANH_TOAN = this;
		}
		
		private void detach_THANH_TOANs(THANH_TOAN entity)
		{
			this.SendPropertyChanging();
			entity.PHUONG_THUC_THANH_TOAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TOUR")]
	public partial class TOUR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STT;
		
		private string _ID_TOUR;
		
		private string _TEN_TOUR;
		
		private string _MO_TA;
		
		private System.DateTime _NGAY_DI;
		
		private System.DateTime _NGAY_VE;
		
		private string _DIA_DIEM_KHOI_HANH;
		
		private string _DIA_DIEM_THAM_QUAN;
		
		private decimal _GIA_NGUOI_LON;
		
		private decimal _GIA_TRE_EM;
		
		private string _HINH_THUC_DI_CHUYEN;
		
		private int _ID_HDV;
		
		private string _ANH_BIA_TOUR;
		
		private int _ID_TRANG_THAI;
		
		private System.Nullable<decimal> _GIAM_GIA;
		
		private EntitySet<DANH_GIA> _DANH_GIAs;
		
		private EntitySet<DAT_TOUR> _DAT_TOURs;
		
		private EntityRef<HUONGDANVIEN> _HUONGDANVIEN;
		
		private EntityRef<TRANG_THAI_TOUR> _TRANG_THAI_TOUR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTTChanging(int value);
    partial void OnSTTChanged();
    partial void OnID_TOURChanging(string value);
    partial void OnID_TOURChanged();
    partial void OnTEN_TOURChanging(string value);
    partial void OnTEN_TOURChanged();
    partial void OnMO_TAChanging(string value);
    partial void OnMO_TAChanged();
    partial void OnNGAY_DIChanging(System.DateTime value);
    partial void OnNGAY_DIChanged();
    partial void OnNGAY_VEChanging(System.DateTime value);
    partial void OnNGAY_VEChanged();
    partial void OnDIA_DIEM_KHOI_HANHChanging(string value);
    partial void OnDIA_DIEM_KHOI_HANHChanged();
    partial void OnDIA_DIEM_THAM_QUANChanging(string value);
    partial void OnDIA_DIEM_THAM_QUANChanged();
    partial void OnGIA_NGUOI_LONChanging(decimal value);
    partial void OnGIA_NGUOI_LONChanged();
    partial void OnGIA_TRE_EMChanging(decimal value);
    partial void OnGIA_TRE_EMChanged();
    partial void OnHINH_THUC_DI_CHUYENChanging(string value);
    partial void OnHINH_THUC_DI_CHUYENChanged();
    partial void OnID_HDVChanging(int value);
    partial void OnID_HDVChanged();
    partial void OnANH_BIA_TOURChanging(string value);
    partial void OnANH_BIA_TOURChanged();
    partial void OnID_TRANG_THAIChanging(int value);
    partial void OnID_TRANG_THAIChanged();
    partial void OnGIAM_GIAChanging(System.Nullable<decimal> value);
    partial void OnGIAM_GIAChanged();
    #endregion
		
		public TOUR()
		{
			this._DANH_GIAs = new EntitySet<DANH_GIA>(new Action<DANH_GIA>(this.attach_DANH_GIAs), new Action<DANH_GIA>(this.detach_DANH_GIAs));
			this._DAT_TOURs = new EntitySet<DAT_TOUR>(new Action<DAT_TOUR>(this.attach_DAT_TOURs), new Action<DAT_TOUR>(this.detach_DAT_TOURs));
			this._HUONGDANVIEN = default(EntityRef<HUONGDANVIEN>);
			this._TRANG_THAI_TOUR = default(EntityRef<TRANG_THAI_TOUR>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TOUR", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_TOUR
		{
			get
			{
				return this._ID_TOUR;
			}
			set
			{
				if ((this._ID_TOUR != value))
				{
					this.OnID_TOURChanging(value);
					this.SendPropertyChanging();
					this._ID_TOUR = value;
					this.SendPropertyChanged("ID_TOUR");
					this.OnID_TOURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_TOUR", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TEN_TOUR
		{
			get
			{
				return this._TEN_TOUR;
			}
			set
			{
				if ((this._TEN_TOUR != value))
				{
					this.OnTEN_TOURChanging(value);
					this.SendPropertyChanging();
					this._TEN_TOUR = value;
					this.SendPropertyChanged("TEN_TOUR");
					this.OnTEN_TOURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MO_TA", DbType="NVarChar(MAX)")]
		public string MO_TA
		{
			get
			{
				return this._MO_TA;
			}
			set
			{
				if ((this._MO_TA != value))
				{
					this.OnMO_TAChanging(value);
					this.SendPropertyChanging();
					this._MO_TA = value;
					this.SendPropertyChanged("MO_TA");
					this.OnMO_TAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_DI", DbType="Date NOT NULL")]
		public System.DateTime NGAY_DI
		{
			get
			{
				return this._NGAY_DI;
			}
			set
			{
				if ((this._NGAY_DI != value))
				{
					this.OnNGAY_DIChanging(value);
					this.SendPropertyChanging();
					this._NGAY_DI = value;
					this.SendPropertyChanged("NGAY_DI");
					this.OnNGAY_DIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_VE", DbType="Date NOT NULL")]
		public System.DateTime NGAY_VE
		{
			get
			{
				return this._NGAY_VE;
			}
			set
			{
				if ((this._NGAY_VE != value))
				{
					this.OnNGAY_VEChanging(value);
					this.SendPropertyChanging();
					this._NGAY_VE = value;
					this.SendPropertyChanged("NGAY_VE");
					this.OnNGAY_VEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIA_DIEM_KHOI_HANH", DbType="NVarChar(100)")]
		public string DIA_DIEM_KHOI_HANH
		{
			get
			{
				return this._DIA_DIEM_KHOI_HANH;
			}
			set
			{
				if ((this._DIA_DIEM_KHOI_HANH != value))
				{
					this.OnDIA_DIEM_KHOI_HANHChanging(value);
					this.SendPropertyChanging();
					this._DIA_DIEM_KHOI_HANH = value;
					this.SendPropertyChanged("DIA_DIEM_KHOI_HANH");
					this.OnDIA_DIEM_KHOI_HANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIA_DIEM_THAM_QUAN", DbType="NVarChar(500)")]
		public string DIA_DIEM_THAM_QUAN
		{
			get
			{
				return this._DIA_DIEM_THAM_QUAN;
			}
			set
			{
				if ((this._DIA_DIEM_THAM_QUAN != value))
				{
					this.OnDIA_DIEM_THAM_QUANChanging(value);
					this.SendPropertyChanging();
					this._DIA_DIEM_THAM_QUAN = value;
					this.SendPropertyChanged("DIA_DIEM_THAM_QUAN");
					this.OnDIA_DIEM_THAM_QUANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIA_NGUOI_LON", DbType="Decimal(18,2) NOT NULL")]
		public decimal GIA_NGUOI_LON
		{
			get
			{
				return this._GIA_NGUOI_LON;
			}
			set
			{
				if ((this._GIA_NGUOI_LON != value))
				{
					this.OnGIA_NGUOI_LONChanging(value);
					this.SendPropertyChanging();
					this._GIA_NGUOI_LON = value;
					this.SendPropertyChanged("GIA_NGUOI_LON");
					this.OnGIA_NGUOI_LONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIA_TRE_EM", DbType="Decimal(18,2) NOT NULL")]
		public decimal GIA_TRE_EM
		{
			get
			{
				return this._GIA_TRE_EM;
			}
			set
			{
				if ((this._GIA_TRE_EM != value))
				{
					this.OnGIA_TRE_EMChanging(value);
					this.SendPropertyChanging();
					this._GIA_TRE_EM = value;
					this.SendPropertyChanged("GIA_TRE_EM");
					this.OnGIA_TRE_EMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINH_THUC_DI_CHUYEN", DbType="NVarChar(100)")]
		public string HINH_THUC_DI_CHUYEN
		{
			get
			{
				return this._HINH_THUC_DI_CHUYEN;
			}
			set
			{
				if ((this._HINH_THUC_DI_CHUYEN != value))
				{
					this.OnHINH_THUC_DI_CHUYENChanging(value);
					this.SendPropertyChanging();
					this._HINH_THUC_DI_CHUYEN = value;
					this.SendPropertyChanged("HINH_THUC_DI_CHUYEN");
					this.OnHINH_THUC_DI_CHUYENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_HDV", DbType="Int NOT NULL")]
		public int ID_HDV
		{
			get
			{
				return this._ID_HDV;
			}
			set
			{
				if ((this._ID_HDV != value))
				{
					if (this._HUONGDANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_HDVChanging(value);
					this.SendPropertyChanging();
					this._ID_HDV = value;
					this.SendPropertyChanged("ID_HDV");
					this.OnID_HDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANH_BIA_TOUR", DbType="NVarChar(255)")]
		public string ANH_BIA_TOUR
		{
			get
			{
				return this._ANH_BIA_TOUR;
			}
			set
			{
				if ((this._ANH_BIA_TOUR != value))
				{
					this.OnANH_BIA_TOURChanging(value);
					this.SendPropertyChanging();
					this._ANH_BIA_TOUR = value;
					this.SendPropertyChanged("ANH_BIA_TOUR");
					this.OnANH_BIA_TOURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TRANG_THAI", DbType="Int NOT NULL")]
		public int ID_TRANG_THAI
		{
			get
			{
				return this._ID_TRANG_THAI;
			}
			set
			{
				if ((this._ID_TRANG_THAI != value))
				{
					if (this._TRANG_THAI_TOUR.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_TRANG_THAIChanging(value);
					this.SendPropertyChanging();
					this._ID_TRANG_THAI = value;
					this.SendPropertyChanged("ID_TRANG_THAI");
					this.OnID_TRANG_THAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIAM_GIA", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> GIAM_GIA
		{
			get
			{
				return this._GIAM_GIA;
			}
			set
			{
				if ((this._GIAM_GIA != value))
				{
					this.OnGIAM_GIAChanging(value);
					this.SendPropertyChanging();
					this._GIAM_GIA = value;
					this.SendPropertyChanged("GIAM_GIA");
					this.OnGIAM_GIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOUR_DANH_GIA", Storage="_DANH_GIAs", ThisKey="ID_TOUR", OtherKey="ID_TOUR")]
		public EntitySet<DANH_GIA> DANH_GIAs
		{
			get
			{
				return this._DANH_GIAs;
			}
			set
			{
				this._DANH_GIAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TOUR_DAT_TOUR", Storage="_DAT_TOURs", ThisKey="ID_TOUR", OtherKey="ID_TOUR")]
		public EntitySet<DAT_TOUR> DAT_TOURs
		{
			get
			{
				return this._DAT_TOURs;
			}
			set
			{
				this._DAT_TOURs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HUONGDANVIEN_TOUR", Storage="_HUONGDANVIEN", ThisKey="ID_HDV", OtherKey="ID_HDV", IsForeignKey=true)]
		public HUONGDANVIEN HUONGDANVIEN
		{
			get
			{
				return this._HUONGDANVIEN.Entity;
			}
			set
			{
				HUONGDANVIEN previousValue = this._HUONGDANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._HUONGDANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HUONGDANVIEN.Entity = null;
						previousValue.TOURs.Remove(this);
					}
					this._HUONGDANVIEN.Entity = value;
					if ((value != null))
					{
						value.TOURs.Add(this);
						this._ID_HDV = value.ID_HDV;
					}
					else
					{
						this._ID_HDV = default(int);
					}
					this.SendPropertyChanged("HUONGDANVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRANG_THAI_TOUR_TOUR", Storage="_TRANG_THAI_TOUR", ThisKey="ID_TRANG_THAI", OtherKey="ID_TRANG_THAI", IsForeignKey=true)]
		public TRANG_THAI_TOUR TRANG_THAI_TOUR
		{
			get
			{
				return this._TRANG_THAI_TOUR.Entity;
			}
			set
			{
				TRANG_THAI_TOUR previousValue = this._TRANG_THAI_TOUR.Entity;
				if (((previousValue != value) 
							|| (this._TRANG_THAI_TOUR.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRANG_THAI_TOUR.Entity = null;
						previousValue.TOURs.Remove(this);
					}
					this._TRANG_THAI_TOUR.Entity = value;
					if ((value != null))
					{
						value.TOURs.Add(this);
						this._ID_TRANG_THAI = value.ID_TRANG_THAI;
					}
					else
					{
						this._ID_TRANG_THAI = default(int);
					}
					this.SendPropertyChanged("TRANG_THAI_TOUR");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DANH_GIAs(DANH_GIA entity)
		{
			this.SendPropertyChanging();
			entity.TOUR = this;
		}
		
		private void detach_DANH_GIAs(DANH_GIA entity)
		{
			this.SendPropertyChanging();
			entity.TOUR = null;
		}
		
		private void attach_DAT_TOURs(DAT_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.TOUR = this;
		}
		
		private void detach_DAT_TOURs(DAT_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.TOUR = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THANH_TOAN")]
	public partial class THANH_TOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_THANH_TOAN;
		
		private int _ID_PHUONG_THUC;
		
		private decimal _SO_TIEN_DA_NHAN;
		
		private int _ID_TRANG_THAI;
		
		private EntitySet<DAT_TOUR> _DAT_TOURs;
		
		private EntityRef<PHUONG_THUC_THANH_TOAN> _PHUONG_THUC_THANH_TOAN;
		
		private EntityRef<TRANG_THAI_THANH_TOAN> _TRANG_THAI_THANH_TOAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_THANH_TOANChanging(int value);
    partial void OnID_THANH_TOANChanged();
    partial void OnID_PHUONG_THUCChanging(int value);
    partial void OnID_PHUONG_THUCChanged();
    partial void OnSO_TIEN_DA_NHANChanging(decimal value);
    partial void OnSO_TIEN_DA_NHANChanged();
    partial void OnID_TRANG_THAIChanging(int value);
    partial void OnID_TRANG_THAIChanged();
    #endregion
		
		public THANH_TOAN()
		{
			this._DAT_TOURs = new EntitySet<DAT_TOUR>(new Action<DAT_TOUR>(this.attach_DAT_TOURs), new Action<DAT_TOUR>(this.detach_DAT_TOURs));
			this._PHUONG_THUC_THANH_TOAN = default(EntityRef<PHUONG_THUC_THANH_TOAN>);
			this._TRANG_THAI_THANH_TOAN = default(EntityRef<TRANG_THAI_THANH_TOAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_THANH_TOAN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_THANH_TOAN
		{
			get
			{
				return this._ID_THANH_TOAN;
			}
			set
			{
				if ((this._ID_THANH_TOAN != value))
				{
					this.OnID_THANH_TOANChanging(value);
					this.SendPropertyChanging();
					this._ID_THANH_TOAN = value;
					this.SendPropertyChanged("ID_THANH_TOAN");
					this.OnID_THANH_TOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PHUONG_THUC", DbType="Int NOT NULL")]
		public int ID_PHUONG_THUC
		{
			get
			{
				return this._ID_PHUONG_THUC;
			}
			set
			{
				if ((this._ID_PHUONG_THUC != value))
				{
					if (this._PHUONG_THUC_THANH_TOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_PHUONG_THUCChanging(value);
					this.SendPropertyChanging();
					this._ID_PHUONG_THUC = value;
					this.SendPropertyChanged("ID_PHUONG_THUC");
					this.OnID_PHUONG_THUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SO_TIEN_DA_NHAN", DbType="Decimal(18,2) NOT NULL")]
		public decimal SO_TIEN_DA_NHAN
		{
			get
			{
				return this._SO_TIEN_DA_NHAN;
			}
			set
			{
				if ((this._SO_TIEN_DA_NHAN != value))
				{
					this.OnSO_TIEN_DA_NHANChanging(value);
					this.SendPropertyChanging();
					this._SO_TIEN_DA_NHAN = value;
					this.SendPropertyChanged("SO_TIEN_DA_NHAN");
					this.OnSO_TIEN_DA_NHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TRANG_THAI", DbType="Int NOT NULL")]
		public int ID_TRANG_THAI
		{
			get
			{
				return this._ID_TRANG_THAI;
			}
			set
			{
				if ((this._ID_TRANG_THAI != value))
				{
					if (this._TRANG_THAI_THANH_TOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_TRANG_THAIChanging(value);
					this.SendPropertyChanging();
					this._ID_TRANG_THAI = value;
					this.SendPropertyChanged("ID_TRANG_THAI");
					this.OnID_TRANG_THAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THANH_TOAN_DAT_TOUR", Storage="_DAT_TOURs", ThisKey="ID_THANH_TOAN", OtherKey="ID_THANH_TOAN")]
		public EntitySet<DAT_TOUR> DAT_TOURs
		{
			get
			{
				return this._DAT_TOURs;
			}
			set
			{
				this._DAT_TOURs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHUONG_THUC_THANH_TOAN_THANH_TOAN", Storage="_PHUONG_THUC_THANH_TOAN", ThisKey="ID_PHUONG_THUC", OtherKey="ID_PHUONG_THUC", IsForeignKey=true)]
		public PHUONG_THUC_THANH_TOAN PHUONG_THUC_THANH_TOAN
		{
			get
			{
				return this._PHUONG_THUC_THANH_TOAN.Entity;
			}
			set
			{
				PHUONG_THUC_THANH_TOAN previousValue = this._PHUONG_THUC_THANH_TOAN.Entity;
				if (((previousValue != value) 
							|| (this._PHUONG_THUC_THANH_TOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHUONG_THUC_THANH_TOAN.Entity = null;
						previousValue.THANH_TOANs.Remove(this);
					}
					this._PHUONG_THUC_THANH_TOAN.Entity = value;
					if ((value != null))
					{
						value.THANH_TOANs.Add(this);
						this._ID_PHUONG_THUC = value.ID_PHUONG_THUC;
					}
					else
					{
						this._ID_PHUONG_THUC = default(int);
					}
					this.SendPropertyChanged("PHUONG_THUC_THANH_TOAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRANG_THAI_THANH_TOAN_THANH_TOAN", Storage="_TRANG_THAI_THANH_TOAN", ThisKey="ID_TRANG_THAI", OtherKey="ID_TRANG_THAI", IsForeignKey=true)]
		public TRANG_THAI_THANH_TOAN TRANG_THAI_THANH_TOAN
		{
			get
			{
				return this._TRANG_THAI_THANH_TOAN.Entity;
			}
			set
			{
				TRANG_THAI_THANH_TOAN previousValue = this._TRANG_THAI_THANH_TOAN.Entity;
				if (((previousValue != value) 
							|| (this._TRANG_THAI_THANH_TOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRANG_THAI_THANH_TOAN.Entity = null;
						previousValue.THANH_TOANs.Remove(this);
					}
					this._TRANG_THAI_THANH_TOAN.Entity = value;
					if ((value != null))
					{
						value.THANH_TOANs.Add(this);
						this._ID_TRANG_THAI = value.ID_TRANG_THAI;
					}
					else
					{
						this._ID_TRANG_THAI = default(int);
					}
					this.SendPropertyChanged("TRANG_THAI_THANH_TOAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DAT_TOURs(DAT_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.THANH_TOAN = this;
		}
		
		private void detach_DAT_TOURs(DAT_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.THANH_TOAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THANH_VIEN")]
	public partial class THANH_VIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_THANH_VIEN;
		
		private string _TEN_THANH_VIEN;
		
		private string _EMAIL_THANH_VIEN;
		
		private string _SDT_THANH_VIEN;
		
		private string _DIA_CHI_THANH_VIEN;
		
		private string _MAT_KHAU;
		
		private System.DateTime _NGAY_TAO;
		
		private EntitySet<ADMIN> _ADMINs;
		
		private EntitySet<DANH_GIA> _DANH_GIAs;
		
		private EntitySet<DAT_TOUR> _DAT_TOURs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_THANH_VIENChanging(int value);
    partial void OnID_THANH_VIENChanged();
    partial void OnTEN_THANH_VIENChanging(string value);
    partial void OnTEN_THANH_VIENChanged();
    partial void OnEMAIL_THANH_VIENChanging(string value);
    partial void OnEMAIL_THANH_VIENChanged();
    partial void OnSDT_THANH_VIENChanging(string value);
    partial void OnSDT_THANH_VIENChanged();
    partial void OnDIA_CHI_THANH_VIENChanging(string value);
    partial void OnDIA_CHI_THANH_VIENChanged();
    partial void OnMAT_KHAUChanging(string value);
    partial void OnMAT_KHAUChanged();
    partial void OnNGAY_TAOChanging(System.DateTime value);
    partial void OnNGAY_TAOChanged();
    #endregion
		
		public THANH_VIEN()
		{
			this._ADMINs = new EntitySet<ADMIN>(new Action<ADMIN>(this.attach_ADMINs), new Action<ADMIN>(this.detach_ADMINs));
			this._DANH_GIAs = new EntitySet<DANH_GIA>(new Action<DANH_GIA>(this.attach_DANH_GIAs), new Action<DANH_GIA>(this.detach_DANH_GIAs));
			this._DAT_TOURs = new EntitySet<DAT_TOUR>(new Action<DAT_TOUR>(this.attach_DAT_TOURs), new Action<DAT_TOUR>(this.detach_DAT_TOURs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_THANH_VIEN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_THANH_VIEN
		{
			get
			{
				return this._ID_THANH_VIEN;
			}
			set
			{
				if ((this._ID_THANH_VIEN != value))
				{
					this.OnID_THANH_VIENChanging(value);
					this.SendPropertyChanging();
					this._ID_THANH_VIEN = value;
					this.SendPropertyChanged("ID_THANH_VIEN");
					this.OnID_THANH_VIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_THANH_VIEN", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string TEN_THANH_VIEN
		{
			get
			{
				return this._TEN_THANH_VIEN;
			}
			set
			{
				if ((this._TEN_THANH_VIEN != value))
				{
					this.OnTEN_THANH_VIENChanging(value);
					this.SendPropertyChanging();
					this._TEN_THANH_VIEN = value;
					this.SendPropertyChanged("TEN_THANH_VIEN");
					this.OnTEN_THANH_VIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL_THANH_VIEN", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string EMAIL_THANH_VIEN
		{
			get
			{
				return this._EMAIL_THANH_VIEN;
			}
			set
			{
				if ((this._EMAIL_THANH_VIEN != value))
				{
					this.OnEMAIL_THANH_VIENChanging(value);
					this.SendPropertyChanging();
					this._EMAIL_THANH_VIEN = value;
					this.SendPropertyChanged("EMAIL_THANH_VIEN");
					this.OnEMAIL_THANH_VIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT_THANH_VIEN", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string SDT_THANH_VIEN
		{
			get
			{
				return this._SDT_THANH_VIEN;
			}
			set
			{
				if ((this._SDT_THANH_VIEN != value))
				{
					this.OnSDT_THANH_VIENChanging(value);
					this.SendPropertyChanging();
					this._SDT_THANH_VIEN = value;
					this.SendPropertyChanged("SDT_THANH_VIEN");
					this.OnSDT_THANH_VIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIA_CHI_THANH_VIEN", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string DIA_CHI_THANH_VIEN
		{
			get
			{
				return this._DIA_CHI_THANH_VIEN;
			}
			set
			{
				if ((this._DIA_CHI_THANH_VIEN != value))
				{
					this.OnDIA_CHI_THANH_VIENChanging(value);
					this.SendPropertyChanging();
					this._DIA_CHI_THANH_VIEN = value;
					this.SendPropertyChanged("DIA_CHI_THANH_VIEN");
					this.OnDIA_CHI_THANH_VIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAT_KHAU", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string MAT_KHAU
		{
			get
			{
				return this._MAT_KHAU;
			}
			set
			{
				if ((this._MAT_KHAU != value))
				{
					this.OnMAT_KHAUChanging(value);
					this.SendPropertyChanging();
					this._MAT_KHAU = value;
					this.SendPropertyChanged("MAT_KHAU");
					this.OnMAT_KHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_TAO", DbType="DateTime NOT NULL")]
		public System.DateTime NGAY_TAO
		{
			get
			{
				return this._NGAY_TAO;
			}
			set
			{
				if ((this._NGAY_TAO != value))
				{
					this.OnNGAY_TAOChanging(value);
					this.SendPropertyChanging();
					this._NGAY_TAO = value;
					this.SendPropertyChanged("NGAY_TAO");
					this.OnNGAY_TAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THANH_VIEN_ADMIN", Storage="_ADMINs", ThisKey="ID_THANH_VIEN", OtherKey="ID_THANH_VIEN")]
		public EntitySet<ADMIN> ADMINs
		{
			get
			{
				return this._ADMINs;
			}
			set
			{
				this._ADMINs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THANH_VIEN_DANH_GIA", Storage="_DANH_GIAs", ThisKey="ID_THANH_VIEN", OtherKey="ID_THANH_VIEN")]
		public EntitySet<DANH_GIA> DANH_GIAs
		{
			get
			{
				return this._DANH_GIAs;
			}
			set
			{
				this._DANH_GIAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THANH_VIEN_DAT_TOUR", Storage="_DAT_TOURs", ThisKey="ID_THANH_VIEN", OtherKey="ID_THANH_VIEN")]
		public EntitySet<DAT_TOUR> DAT_TOURs
		{
			get
			{
				return this._DAT_TOURs;
			}
			set
			{
				this._DAT_TOURs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ADMINs(ADMIN entity)
		{
			this.SendPropertyChanging();
			entity.THANH_VIEN = this;
		}
		
		private void detach_ADMINs(ADMIN entity)
		{
			this.SendPropertyChanging();
			entity.THANH_VIEN = null;
		}
		
		private void attach_DANH_GIAs(DANH_GIA entity)
		{
			this.SendPropertyChanging();
			entity.THANH_VIEN = this;
		}
		
		private void detach_DANH_GIAs(DANH_GIA entity)
		{
			this.SendPropertyChanging();
			entity.THANH_VIEN = null;
		}
		
		private void attach_DAT_TOURs(DAT_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.THANH_VIEN = this;
		}
		
		private void detach_DAT_TOURs(DAT_TOUR entity)
		{
			this.SendPropertyChanging();
			entity.THANH_VIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRANG_THAI_TOUR")]
	public partial class TRANG_THAI_TOUR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_TRANG_THAI;
		
		private string _TEN_TRANG_THAI;
		
		private EntitySet<TOUR> _TOURs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_TRANG_THAIChanging(int value);
    partial void OnID_TRANG_THAIChanged();
    partial void OnTEN_TRANG_THAIChanging(string value);
    partial void OnTEN_TRANG_THAIChanged();
    #endregion
		
		public TRANG_THAI_TOUR()
		{
			this._TOURs = new EntitySet<TOUR>(new Action<TOUR>(this.attach_TOURs), new Action<TOUR>(this.detach_TOURs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TRANG_THAI", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_TRANG_THAI
		{
			get
			{
				return this._ID_TRANG_THAI;
			}
			set
			{
				if ((this._ID_TRANG_THAI != value))
				{
					this.OnID_TRANG_THAIChanging(value);
					this.SendPropertyChanging();
					this._ID_TRANG_THAI = value;
					this.SendPropertyChanged("ID_TRANG_THAI");
					this.OnID_TRANG_THAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_TRANG_THAI", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TEN_TRANG_THAI
		{
			get
			{
				return this._TEN_TRANG_THAI;
			}
			set
			{
				if ((this._TEN_TRANG_THAI != value))
				{
					this.OnTEN_TRANG_THAIChanging(value);
					this.SendPropertyChanging();
					this._TEN_TRANG_THAI = value;
					this.SendPropertyChanged("TEN_TRANG_THAI");
					this.OnTEN_TRANG_THAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRANG_THAI_TOUR_TOUR", Storage="_TOURs", ThisKey="ID_TRANG_THAI", OtherKey="ID_TRANG_THAI")]
		public EntitySet<TOUR> TOURs
		{
			get
			{
				return this._TOURs;
			}
			set
			{
				this._TOURs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TOURs(TOUR entity)
		{
			this.SendPropertyChanging();
			entity.TRANG_THAI_TOUR = this;
		}
		
		private void detach_TOURs(TOUR entity)
		{
			this.SendPropertyChanging();
			entity.TRANG_THAI_TOUR = null;
		}
	}
}
#pragma warning restore 1591
