<?xml version="1.0" encoding="utf-8"?><Database Name="pacifictravel" Class="databaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.ADMIN" Member="ADMINs">
    <Type Name="ADMIN">
      <Column Name="ID_ADMIN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_THANH_VIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ADMIN_BAI_VIET" Member="BAI_VIETs" ThisKey="ID_ADMIN" OtherKey="ID_ADMIN" Type="BAI_VIET" />
      <Association Name="THANH_VIEN_ADMIN" Member="THANH_VIEN" ThisKey="ID_THANH_VIEN" OtherKey="ID_THANH_VIEN" Type="THANH_VIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TRANG_THAI_THANH_TOAN" Member="TRANG_THAI_THANH_TOANs">
    <Type Name="TRANG_THAI_THANH_TOAN">
      <Column Name="ID_TRANG_THAI" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TEN_TRANG_THAI" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="TRANG_THAI_THANH_TOAN_THANH_TOAN" Member="THANH_TOANs" ThisKey="ID_TRANG_THAI" OtherKey="ID_TRANG_THAI" Type="THANH_TOAN" />
    </Type>
  </Table>
  <Table Name="dbo.BAI_VIET" Member="BAI_VIETs">
    <Type Name="BAI_VIET">
      <Column Name="ID_BAI_VIET" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="THOI_GIAN_TAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NOI_DUNG" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ID_ADMIN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ANH_BIA_BAI_VIET" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="ADMIN_BAI_VIET" Member="ADMIN" ThisKey="ID_ADMIN" OtherKey="ID_ADMIN" Type="ADMIN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DANH_GIA" Member="DANH_GIAs">
    <Type Name="DANH_GIA">
      <Column Name="ID_DANH_GIA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SO_LUONG_SAO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NOI_DUNG_DANH_GIA" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ID_TOUR" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ID_THANH_VIEN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TOUR_DANH_GIA" Member="TOUR" ThisKey="ID_TOUR" OtherKey="ID_TOUR" Type="TOUR" IsForeignKey="true" />
      <Association Name="THANH_VIEN_DANH_GIA" Member="THANH_VIEN" ThisKey="ID_THANH_VIEN" OtherKey="ID_THANH_VIEN" Type="THANH_VIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DAT_TOUR" Member="DAT_TOURs">
    <Type Name="DAT_TOUR">
      <Column Name="STT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_DAT_TOUR" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="THOI_GIAN_DAT" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TONG_SO_TIEN" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="ID_TOUR" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ID_THANH_TOAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_THANH_VIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ID_LOAI" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="LOAI_TOUR_DAT_TOUR" Member="LOAI_TOUR" ThisKey="ID_LOAI" OtherKey="ID_LOAI" Type="LOAI_TOUR" IsForeignKey="true" />
      <Association Name="TOUR_DAT_TOUR" Member="TOUR" ThisKey="ID_TOUR" OtherKey="ID_TOUR" Type="TOUR" IsForeignKey="true" />
      <Association Name="THANH_TOAN_DAT_TOUR" Member="THANH_TOAN" ThisKey="ID_THANH_TOAN" OtherKey="ID_THANH_TOAN" Type="THANH_TOAN" IsForeignKey="true" />
      <Association Name="THANH_VIEN_DAT_TOUR" Member="THANH_VIEN" ThisKey="ID_THANH_VIEN" OtherKey="ID_THANH_VIEN" Type="THANH_VIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HUONGDANVIEN" Member="HUONGDANVIENs">
    <Type Name="HUONGDANVIEN">
      <Column Name="ID_HDV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HO_TEN_HDV" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SDT_HDV" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="EMAIL_HDV" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DIA_CHI_HDV" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="HUONGDANVIEN_TOUR" Member="TOURs" ThisKey="ID_HDV" OtherKey="ID_HDV" Type="TOUR" />
    </Type>
  </Table>
  <Table Name="dbo.LOAI_TOUR" Member="LOAI_TOURs">
    <Type Name="LOAI_TOUR">
      <Column Name="ID_LOAI" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TEN_LOAI" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="LOAI_TOUR_DAT_TOUR" Member="DAT_TOURs" ThisKey="ID_LOAI" OtherKey="ID_LOAI" Type="DAT_TOUR" />
    </Type>
  </Table>
  <Table Name="dbo.PHUONG_THUC_THANH_TOAN" Member="PHUONG_THUC_THANH_TOANs">
    <Type Name="PHUONG_THUC_THANH_TOAN">
      <Column Name="ID_PHUONG_THUC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TEN_PHUONG_THUC" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="PHUONG_THUC_THANH_TOAN_THANH_TOAN" Member="THANH_TOANs" ThisKey="ID_PHUONG_THUC" OtherKey="ID_PHUONG_THUC" Type="THANH_TOAN" />
    </Type>
  </Table>
  <Table Name="dbo.TOUR" Member="TOURs">
    <Type Name="TOUR">
      <Column Name="STT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_TOUR" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TEN_TOUR" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MO_TA" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NGAY_DI" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NGAY_VE" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DIA_DIEM_KHOI_HANH" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DIA_DIEM_THAM_QUAN" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="GIA_NGUOI_LON" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="GIA_TRE_EM" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="HINH_THUC_DI_CHUYEN" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ID_HDV" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ANH_BIA_TOUR" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ID_TRANG_THAI" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GIAM_GIA" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="TOUR_DANH_GIA" Member="DANH_GIAs" ThisKey="ID_TOUR" OtherKey="ID_TOUR" Type="DANH_GIA" />
      <Association Name="TOUR_DAT_TOUR" Member="DAT_TOURs" ThisKey="ID_TOUR" OtherKey="ID_TOUR" Type="DAT_TOUR" />
      <Association Name="HUONGDANVIEN_TOUR" Member="HUONGDANVIEN" ThisKey="ID_HDV" OtherKey="ID_HDV" Type="HUONGDANVIEN" IsForeignKey="true" />
      <Association Name="TRANG_THAI_TOUR_TOUR" Member="TRANG_THAI_TOUR" ThisKey="ID_TRANG_THAI" OtherKey="ID_TRANG_THAI" Type="TRANG_THAI_TOUR" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.THANH_TOAN" Member="THANH_TOANs">
    <Type Name="THANH_TOAN">
      <Column Name="ID_THANH_TOAN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_PHUONG_THUC" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SO_TIEN_DA_NHAN" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="ID_TRANG_THAI" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="THANH_TOAN_DAT_TOUR" Member="DAT_TOURs" ThisKey="ID_THANH_TOAN" OtherKey="ID_THANH_TOAN" Type="DAT_TOUR" />
      <Association Name="PHUONG_THUC_THANH_TOAN_THANH_TOAN" Member="PHUONG_THUC_THANH_TOAN" ThisKey="ID_PHUONG_THUC" OtherKey="ID_PHUONG_THUC" Type="PHUONG_THUC_THANH_TOAN" IsForeignKey="true" />
      <Association Name="TRANG_THAI_THANH_TOAN_THANH_TOAN" Member="TRANG_THAI_THANH_TOAN" ThisKey="ID_TRANG_THAI" OtherKey="ID_TRANG_THAI" Type="TRANG_THAI_THANH_TOAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.THANH_VIEN" Member="THANH_VIENs">
    <Type Name="THANH_VIEN">
      <Column Name="ID_THANH_VIEN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TEN_THANH_VIEN" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="EMAIL_THANH_VIEN" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SDT_THANH_VIEN" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="DIA_CHI_THANH_VIEN" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="MAT_KHAU" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="NGAY_TAO" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="THANH_VIEN_ADMIN" Member="ADMINs" ThisKey="ID_THANH_VIEN" OtherKey="ID_THANH_VIEN" Type="ADMIN" />
      <Association Name="THANH_VIEN_DANH_GIA" Member="DANH_GIAs" ThisKey="ID_THANH_VIEN" OtherKey="ID_THANH_VIEN" Type="DANH_GIA" />
      <Association Name="THANH_VIEN_DAT_TOUR" Member="DAT_TOURs" ThisKey="ID_THANH_VIEN" OtherKey="ID_THANH_VIEN" Type="DAT_TOUR" />
    </Type>
  </Table>
  <Table Name="dbo.TRANG_THAI_TOUR" Member="TRANG_THAI_TOURs">
    <Type Name="TRANG_THAI_TOUR">
      <Column Name="ID_TRANG_THAI" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TEN_TRANG_THAI" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="TRANG_THAI_TOUR_TOUR" Member="TOURs" ThisKey="ID_TRANG_THAI" OtherKey="ID_TRANG_THAI" Type="TOUR" />
    </Type>
  </Table>
</Database>